const Product = require("../models/Product");

// Create new product (with optional image upload)
// const addProduct = async (req, res) => {
//   try {
//     const { name, description, price, category } = req.body;

//     if (!name || !price) {
//       return res.status(400).json({ message: "Name and price are required" });
//     }

//     const image = req.file ? req.file.filename : null; 
//     const product = new Product({ name, description, price, category, image });
//     await product.save();

//     res.status(201).json(product);
//   } catch (error) {
//     res.status(500).json({ message: error.message });
//   }
// };
const addProduct = async (req, res) => {
  try {
    const { name, description, price, category } = req.body;

    // DEBUG: Check if the file is actually reaching the controller
    console.log("Uploaded File:", req.file); 

    let imageUrl = "assets/image.png"; // Start with default
    if (req.file) {
      // Use the filename generated by your uploadMiddleware
      imageUrl = `/uploads/${req.file.filename}`; 
    }

    const product = new Product({ 
      name, 
      description, 
      price, 
      category, 
      imageUrl  // This will now be "/uploads/12345.jpg"
    });

    await product.save();
    res.status(201).json(product);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

// Get all products
const getProducts = async (req, res) => {
  try {
    const products = await Product.find();
    res.json(products);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

// Get product by ID or Name
const getProductByIdOrName = async (req, res) => {
  try {
    const { prodID_OR_ProdName } = req.params;
    let product;

    // Check if param looks like a MongoDB ObjectId
    if (prodID_OR_ProdName.match(/^[0-9a-fA-F]{24}$/)) {
      product = await Product.findById(prodID_OR_ProdName);
    } else {
      product = await Product.findOne({ name: prodID_OR_ProdName });
    }

    if (!product) return res.status(404).json({ message: "Product not found" });
    res.json(product);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

// Update product (partial update, with optional new image)
const updateProduct = async (req, res) => {
  try {
    const { id } = req.params;
    
    // 1. Spread the text fields (name, price, etc.) from req.body
    const updateData = { ...req.body };

    // 2. If a new file is uploaded, update the 'imageUrl' field
    if (req.file) {
      // Use 'imageUrl' (matches your Schema) and include the /uploads/ prefix
      updateData.imageUrl = `/uploads/${req.file.filename}`;
    }

    // 3. Find and update
    const product = await Product.findByIdAndUpdate(
      id, 
      updateData, 
      { new: true, runValidators: true } // runValidators ensures price/name rules still apply
    );

    if (!product) {
      return res.status(404).json({ message: "Product not found" });
    }

    res.json(product);
  } catch (error) {
    console.error("Update Error:", error);
    res.status(500).json({ message: error.message });
  }
};

// Delete product
const deleteProduct = async (req, res) => {
  try {
    const { id } = req.params;
    const product = await Product.findByIdAndDelete(id);
    if (!product) return res.status(404).json({ message: "Product not found" });

    res.json({ message: "Product deleted successfully" });
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

module.exports = { 
  addProduct, 
  getProducts, 
  getProductByIdOrName, 
  updateProduct, 
  deleteProduct 
};
